//! 插件协议的单一事实源。运行时校验、JSON Schema、生成文档和内置插件检查
//! 都从这些常量派生，避免三处各维护一份枚举。

use std::path::Path;

pub const RUNTIMES: &[&str] = &["lua"];
pub const LIVE_PERMISSIONS: &[&str] = &[
    "bus",
    "log",
    "serial",
    "ui",
    "storage",
    "timer",
    "testing",
    "dialog",
    "fs.read.user_selected",
    "task",
    "config",
];
pub const REPLAY_PERMISSIONS: &[&str] = &["log", "storage"];
pub const PANEL_KINDS: &[&str] = &["chart", "form", "attitude", "gauge", "table"];
pub const UI_SLOTS: &[&str] = &[
    "send.toolbar",
    "top_bar.left",
    "top_bar.right",
    "status_bar.left",
    "status_bar.right",
];
pub const UI_KINDS: &[&str] = &[
    "button",
    "small_button",
    "separator",
    "label",
    "status",
    "toggle",
    "progress",
];
pub const SETTING_KINDS: &[&str] = &[
    "text", "number", "boolean", "checkbox", "select", "slider", "textarea", "serial",
];

pub fn generated_reference() -> String {
    format!(
        "<!-- generated by: cargo run -p tool-extension --example sync_plugin_spec -->\n\
# 插件协议枚举（自动生成）\n\n\
- runtime: {}\n\
- live permissions: {}\n\
- replay permissions: {}\n\
- panel kinds: {}\n\
- UI slots: {}\n\
- UI kinds: {}\n\
- setting kinds: {}\n",
        RUNTIMES.join(", "),
        LIVE_PERMISSIONS.join(", "),
        REPLAY_PERMISSIONS.join(", "),
        PANEL_KINDS.join(", "),
        UI_SLOTS.join(", "),
        UI_KINDS.join(", "),
        SETTING_KINDS.join(", ")
    )
}

pub fn synchronize_repository(root: &Path) -> Result<(), String> {
    let schema_path = root.join("plugins/plugin.schema.json");
    let mut schema: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&schema_path).map_err(|e| e.to_string())?)
            .map_err(|e| e.to_string())?;
    set_enum(
        &mut schema,
        &["properties", "api_version", "enum"],
        crate::manifest::SUPPORTED_PLUGIN_API_VERSIONS,
    )?;
    set_enum(&mut schema, &["properties", "runtime", "enum"], RUNTIMES)?;
    set_enum(
        &mut schema,
        &["$defs", "permission", "enum"],
        LIVE_PERMISSIONS,
    )?;
    set_enum(
        &mut schema,
        &["$defs", "replayPermission", "enum"],
        REPLAY_PERMISSIONS,
    )?;
    set_enum(
        &mut schema,
        &["$defs", "panelContribution", "properties", "kind", "enum"],
        PANEL_KINDS,
    )?;
    set_enum(
        &mut schema,
        &["$defs", "uiContribution", "properties", "slot", "enum"],
        UI_SLOTS,
    )?;
    set_enum(
        &mut schema,
        &["$defs", "uiContribution", "properties", "kind", "enum"],
        UI_KINDS,
    )?;
    set_enum(
        &mut schema,
        &["$defs", "setting", "properties", "kind", "enum"],
        SETTING_KINDS,
    )?;
    let schema_text = serde_json::to_string_pretty(&schema).map_err(|e| e.to_string())? + "\n";
    std::fs::write(schema_path, schema_text).map_err(|e| e.to_string())?;
    std::fs::write(
        root.join("docs/plugin-spec.generated.md"),
        generated_reference(),
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

fn set_enum(root: &mut serde_json::Value, path: &[&str], values: &[&str]) -> Result<(), String> {
    let mut current = root;
    for segment in path {
        current = current
            .get_mut(*segment)
            .ok_or_else(|| format!("schema path missing: {}", path.join(".")))?;
    }
    *current = serde_json::Value::Array(
        values
            .iter()
            .map(|v| serde_json::Value::String((*v).to_owned()))
            .collect(),
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_reference_is_checked_in() {
        assert_eq!(
            include_str!("../../../docs/plugin-spec.generated.md"),
            generated_reference()
        );
    }

    #[test]
    fn schema_enums_match_runtime_spec() {
        let schema: serde_json::Value =
            serde_json::from_str(include_str!("../../../plugins/plugin.schema.json")).unwrap();
        let cases: &[(&[&str], &[&str])] = &[
            (&["$defs", "permission", "enum"], LIVE_PERMISSIONS),
            (&["$defs", "replayPermission", "enum"], REPLAY_PERMISSIONS),
            (
                &["$defs", "panelContribution", "properties", "kind", "enum"],
                PANEL_KINDS,
            ),
            (
                &["$defs", "uiContribution", "properties", "slot", "enum"],
                UI_SLOTS,
            ),
            (
                &["$defs", "uiContribution", "properties", "kind", "enum"],
                UI_KINDS,
            ),
            (
                &["$defs", "setting", "properties", "kind", "enum"],
                SETTING_KINDS,
            ),
        ];
        for (path, expected) in cases {
            let mut value = &schema;
            for segment in *path {
                value = &value[*segment];
            }
            let actual: Vec<&str> = value
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_str().unwrap())
                .collect();
            assert_eq!(&actual, expected, "{}", path.join("."));
        }
    }
}
