[package]
name = "tool-updater"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
dirs-next = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
log.workspace = true

reqwest = { version = "0.12", features = ["json", "native-tls", "rustls-tls-webpki-roots", "system-proxy"], default-features = false }
tokio = { version = "1", features = ["time"] }
zip = "2"
sha2 = "0.10"
url = "2"

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_System_Registry",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
tempfile = "3"
